### ISSUE TITLE
The change in RamlNavigatorFactory made ram_doc config parameter useless

### ISSUE THREAD

**Issue by AliochaRyzhkov** [GoIntegro/hateoas-bundle#66]
After this commit https://github.com/GoIntegro/hateoas-bundle/commit/e2aafe90aa5e069e234e9233f68748d590c4b054 ram_doc became useless.
Isn't it a bad idea to hard code the name and path of raml file?

**Comment by skqr** [comment]
Let's reopen if required. Thanks again!
