### ISSUE TITLE
Release process and versioning

### ISSUE THREAD

**Issue by titolendable** [GoIntegro/hateoas-bundle#70]
I would like to clarify the release process and versioning of this amazing bundle. Unfortunately, the configuration changed in a non backwards compatible way from version 0.9.10 to the latest stable version 0.9.21, the option json_api does not exist anymore. I would assume that such a change should require a new major version, definitely not just an increase of the patch number. At the moment, on my project, I added ~0.9, and this caused things to break badly. What are the intents for the future? Should I lock on composer the version?

**Comment by skqr** [comment]
@titolendable Totally right, my bad. I've been rushing last week and might have made more than one hideous errors like that.

@acmenna, can you add some tags for this?

**Comment by skqr** [comment]
@acmenna, where you able to check this out?

**Comment by acmenna** [comment]
@titolendable: Unfortunately, we cannot amend it because we could affect other users. Please, lock the version in your composer.json unless you were able to upgrade. In addition, we've created 0.10.0 that will reflect the latest development changes.
Sorry for any inconvenience.

**Comment by titolendable** [comment]
@acmenna that's exactly what I did, it solved my problem, hopefully this problem will not happen again in the future, keep up the good work.

**Comment by skqr** [comment]
Thanks, @acmenna! And thanks, @titolendable!

We'll try to be smarter about versioning next time. It was definitely a n00b mistake :smile_cat:
