### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by JDruery** [GoIntegro/hateoas-bundle#75]
I installed the hateoas bundle for symfony2. I tried configuring myself, and then I tried the example bundle. In both cases, the following error is returned for any get request:

Catchable Fatal Error: Argument 4 passed to GoIntegro\Hateoas\JsonApi\Request\Parser::__construct() must be an instance of GoIntegro\Hateoas\JsonApi\Request\SortingParser, instance of GoIntegro\Hateoas\JsonApi\Request\PaginationParser given, called in G:\Content\Work\Website\wamp\www\sf2\app\cache\dev\appDevDebugProjectContainer.php on line 2082 and defined in G:\Content\Work\Website\wamp\www\sf2\vendor\gointegro\hateoas\GoIntegro\Hateoas\JsonApi\Request\Parser.php line 120 (500 Internal Server Error)

**Comment by JDruery** [comment]
I noticed that this error is already fixed in dev-master. Thanks for an excellent and very useful bundle!

**Comment by skqr** [comment]
@acmenna @chebbix

**Comment by acmenna** [comment]
:)
